sudo: false
language: cpp
script:
- g++ --version
- make -C example
notifications:
  slack:
    secure: ilxeE0dLyEqvlEqvsyOQXjEnWrEK9r1bNR6aM+qO04JxDR6AzUfUMqxtA4GDCKkyj/rQkI0YZ5BdSRehxNAqKdtk4UuPVW+dggzIu2OFSXokPpDPPgFuPYlaVDQOReO4NCXzevaTspu/4Tiih24ENCAg1VRPyY7Yhe2SHhrKu1ShNiHDoSprb7UpHlUcrd1zD9BCQu2c0RHkoZDZSDPKTpdsiNLF5x1P0k9j4mHrCniRLKhShDjH6aRe+C41YojM1Gm+wsGahl2Pm43ue2xp77iXCIVcd/+yuFLUqun50LxH0gnmNLfSTZzWfOI/nGjg1Ug51/B167UcREY61BqX4HaimFDygOwiV1+FZkzVIUgFzoWJjahIxUZ82DgzQ6EMTbogww6B7ZJjy/JpThkI7xoPeGdtE/Qmw+LaeLCwCKTWXc+jzO8F3aZtR4spfkrnzTnpc9IFAXwQd7tdEJRN16ezOdsVZ2mDXtrgfIjCYMtr9tflBdGJ7Y4lt71TjnAWftV7KNxqcO1QUCP7tZl5iz7hA742d+fYcTdxZ1YW1QyLSM8+58UsNbqEvncHCRsr2NNtdHZnUWWypa9lEqq6mqAmKsTVfnBeds+PxxGm87ZWHlXEGfU7w2Pw0RuQvjUuc3AngvoVqaW0yGKLwI9DdE3vANqKD8KkbKsnr0RnwGE=
